# Configuração mínima para CI. Ajuste linters conforme necessidade.
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false  # permite _ = para ignorar erro explicitamente (ex.: respostas HTTP já enviadas, audit best-effort)
